export const FETCH_TASKS = 'FETCH_TASKS';
‍export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
‍export const FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE';
‍export const CREATE_TASK = 'CREATE_TASK';
‍export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
‍export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE';